name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/profile-summary-cards.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Renew profile page data
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          UTC_OFFSET: 8
          USERNAME: ${{ github.repository_owner }}
